# version: "3"
services:

  db:
    image: mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD:passtoflint
    - MYSQL_DATABASE:testdb
    - USERID:1000
    - GROUPD:1000

    ports:
    - "3306:3306"

    container_name: mysql

    volumes:
    - ./data:/var/lib/mysql

#    restart: always
